### ISSUE TITLE
Cannot read property 'slick' of undefined

### ISSUE THREAD

**Issue by namrastanov** [devmark/ngx-slick#24] opened 2017-12-14 18:18 UTC
Hi.

If there are no items in the slick element we get the error "Cannot read property 'slick' of undefined" when try to leave the page.

You should check for undefined in **unslick()** method

**Comment by iphilippenko** [comment] 2017-12-28 10:04
the same for me

**Comment by oveshparasara** [comment] 2018-01-22 05:58
ngx-slick.umd.js In which there are two code blocks:
1.

`SlickComponent.prototype.ngOnDestroy = function () {
        this.unslick();
    };`
SlickItemDirective.prototype.ngOnDestroy = function () {
        this.carousel.removeSlide(this)

so the real problem is if we are using "slick" inside OneComponent and then we are navigating to TwoComponent, then due to routing OneComponent get destroys along with our "slick" configuration variable.
And after that our "slick" library runs above two blocks which need component's slick configuration, which is not available because it's already destroyed and we get mentioned error.(Cannot read property 'slick' of undefined)

**Comment by depiction** [comment] 2018-01-25 04:11
This is a duplicate of https://github.com/devmark/ngx-slick/issues/6

You can use the ngIf structural directive to only include the element or component containing the carousel if there is at least one slide.

**Comment by feof** [comment] 2018-02-06 22:00
depiction:you answer always same. The problem born when leave a view that has a slide for a new view. Do you explain me how I should use that ngif?

I have a template:
  <a [routerLink]="['/event', 3]">bye bye</a>
  <div class="card">
    <h5 class="card-header">..</h5>
    <div class="card-block">
      <ngx-slick *ngIf="slides && slides.length" class="carousel" #slickModal="slick-modal" [config]="slideConfig">
        <div ngxSlickItem *ngFor="let slide of slides[0]" class="slide">
          ..
        </div>
      </ngx-slick>
    </div>
  </div>

If a click on element a, it crash.

**Comment by depiction** [comment] 2018-02-06 22:14
@feof In my application I get this error if a user tries to navigate to another view (regardless of whether or not the new view has a carousel or not) before slide data has been received.

The following code worked for me.

I'm getting slide data from an API in the parent component. Once a response from the API has been received, I set loaded to true and pass the slides array to my carousel component. 

```
<ng-container *ngIf="loaded else loading">
    <app-carousel [slides]="slides" *ngIf="(slides && slides.length)"></app-carousel>
</ng-container>
```

**Comment by feof** [comment] 2018-02-06 22:23
Your context is very specific.
All persons, except you, have my same problem.
Tomorrow I see the source code. 
Is app-carousel a directive ?
I do not know why you do not have this problem

**Comment by depiction** [comment] 2018-02-06 22:27
```app-carousel``` is a component.

When creating a component using the Angular CLI, the component's selector, by default, is always "app-[component-name]".

Feel free to try my technique, which requires moving the carousel to a separate component.

**Comment by feof** [comment] 2018-02-06 22:35
Also I have a separate component. I have <component> </ component> and inside ngx-slick. you use that slides, I do not know what to do. However, I think the author left the project.

**Comment by devmark** [comment] 2018-07-11 08:01
Closed. open new issue if any question.

**Closed by devmark** 2018-07-11 08:01 UTC
